=== YThibos/HDisk/Oplossingen voor Johan/XML Test Yannick/cursisten.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:vdab="http://www.vdab.be/cursisten"
        targetNamespace="http://www.vdab.be/cursisten" elementFormDefault="qualified">
    
    <!-- SIMPLE TYPES -->
    <simpleType name="nonEmptyString">
        <restriction base="string">
            <!-- 'Alles behalve witruimte, minstens 1x -->
            <pattern value="\S+" />
        </restriction>
    </simpleType>
    
    <simpleType name="Emailaddress">
        <restriction base="string">
            <!-- '[tekenreeks]+@[tekenreeks]+.[a-z]+ -->
            <pattern value=".+@.+\.[a-z]+" />
        </restriction>
    </simpleType>
    
    <simpleType name="Geboortedatum">
        <restriction base="date">
            <minInclusive value="1950-01-01" />
        </restriction>
    </simpleType>
    
    <simpleType name="Traject">
        <restriction base="string">
            <enumeration value="Java" />
            <enumeration value="C#" />
            <enumeration value="PHP" />
        </restriction>
    </simpleType>
    
    <!-- CURSIST DEFINITON -->
    <complexType name="Cursist">
        <all>
            <element name="voornaam" type="vdab:nonEmptyString" />
            <element name="familienaam" type="vdab:nonEmptyString" />
            <element name="email" type="vdab:Emailaddress" />
            <element name="geboren" type="vdab:Geboortedatum" />
            <element name="traject" type="vdab:Traject" />
        </all>
    </complexType>
    
    <!-- ROOTNODE: Bevat de 'cursisten' -->
    <complexType name="Rootnode">
        <sequence>
            <element name="cursist" type="vdab:Cursist" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <!-- ROOTNODE & KEY DEFINITIONS -->    
    <element name="root" type="vdab:Rootnode">
        <key name="emailKey">
            <selector xpath="vdab:cursist" />
            <field xpath="vdab:email" />
        </key>
    </element>
    
</schema>

=== YThibos/HDisk/Oplossingen voor Johan/XML Test Yannick/cursisten.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="http://www.vdab.be/cursisten"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.vdab.be/cursisten cursisten.xsd">
    
    <cursist>
        <voornaam>Joe</voornaam>
        <familienaam>Dalton</familienaam>
        <email>joe@daltons.org</email>
        <geboren>1966-08-01</geboren>
        <traject>Java</traject>
    </cursist>
    
    <cursist>
        <voornaam>Jack</voornaam>
        <familienaam>Dalton</familienaam>
        <email>jack@daltons.org</email>
        <geboren>1964-08-28</geboren>
        <traject>C#</traject>
    </cursist>
    
    <cursist>
        <voornaam>Lucky</voornaam>
        <familienaam>Luke</familienaam>
        <email>lucky.luke@goodones.org</email>
        <geboren>1965-01-31</geboren>
        <traject>PHP</traject>
    </cursist>

    <cursist>
        <!-- voornaam start met tab -->
        <voornaam>Averell</voornaam>
        <familienaam>§€!è%Dalton</familienaam>
        <!-- ongeldig email -->
        <email>averell@daltons.!</email>
        <!-- 1949-12-31 > 1950-01-01 -->
        <geboren>1949-12-31</geboren>
        <!-- C++ niet in enum -->
        <traject>C++</traject>
    </cursist>
    
    <cursist>
        <voornaam>Averell</voornaam>
        <familienaam>Dalton</familienaam>
        <!-- dupe key -->
        <email>joe@daltons.org</email>
        <geboren>1967-02-14</geboren>
        <traject>Java</traject>
    </cursist>

</root>
