=== YThibos/HDisk/Modules/9 - XML/XMLFundamentalsTakenMateriaal/Keynode.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:vdab="http://www.vdab.be/Keynode"
        targetNamespace="http://www.vdab.be/Keynode" elementFormDefault="qualified">
    
    <!-- TYPE1 DEF -->
    <complexType name="Type1">
        <sequence>
            <element name="intElement" type="integer"/>
            <element name="strElement" type="string"/>
        </sequence>
        <attribute name="intAttrib" type="integer" use="required"/>
        <attribute name="strAttrib" type="string" use="required"/>
    </complexType>
    
    <!-- TYPE2 DEF -->
    <complexType name="Type2">
        <sequence>
            <element name="intElement" type="integer"/>
            <element name="strElement" type="string"/>
        </sequence>
        <attribute name="intAttrib" type="integer" use="required"/>
        <attribute name="strAttrib" type="string" use="required"/>
    </complexType>
    
    <!-- TYPE1 PARENT -->
    <complexType name="Typeones">
        <sequence>
            <element name="type1" type="vdab:Type1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- TYPE2 PARENT -->
    <complexType name="Typetwos">
        <sequence>
            <element name="type2" type="vdab:Type2" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!--ROOT DEFINITION -->
    <complexType name="Rootnode">
        <sequence>
            <element name="typeones" type="vdab:Typeones"/>
            <element name="typetwos" type="vdab:Typetwos"/>
        </sequence>
    </complexType>
    
    <!-- ROOT ELEMENT EN KEY DEF's -->
    <element name="root" type="vdab:Rootnode">
        <key name="type1key">
            <selector xpath="vdab:typeones/vdab:type1"/>
            <field xpath="vdab:strElement"/>
        </key>
        <key name="type2key">
            <selector xpath="vdab:typetwos/vdab:type2"/>
            <field xpath="vdab:strElement"/>
        </key>
        <keyref name="type12ref" refer="vdab:type2key">
            <selector xpath="vdab:typeones/vdab:type1"/>
            <field xpath="vdab:strElement"/>
        </keyref>
    </element>
    
</schema>

=== YThibos/HDisk/Modules/9 - XML/XMLFundamentalsTakenMateriaal/Keynode.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="http://www.vdab.be/Keynode"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.vdab.be/Keynode Keynode.xsd">
    <typeones>
        <type1 intAttrib="1" strAttrib="waarde1">
            <intElement>1</intElement>
            <strElement>waarde1</strElement>
        </type1>
        <type1 intAttrib="2" strAttrib="waarde2">
            <intElement>2</intElement>
            <strElement>waarde2</strElement>
        </type1>
        <type1 intAttrib="3" strAttrib="waarde3">
            <intElement>3</intElement>
            <strElement>waarde5</strElement>
        </type1>
    </typeones>

    <typetwos>
        <type2 intAttrib="1" strAttrib="waarde1">
            <intElement>1</intElement>
            <strElement>waarde1</strElement>
        </type2>
        <type2 intAttrib="2" strAttrib="waarde2">
            <intElement>2</intElement>
            <strElement>waarde2</strElement>
        </type2>
        <type2 intAttrib="3" strAttrib="waarde3">
            <intElement>3</intElement>
            <strElement>waarde3</strElement>
        </type2>
        <type2 intAttrib="4" strAttrib="waarde4">
            <intElement>4</intElement>
            <strElement>waarde4</strElement>
        </type2>
    </typetwos>
</root>
